name:  GPS-Quests
main: me.pikamug.gpsquests.GPSQuests
version: "1.0"
api-version: 1.13
description: Navigate Quests objectives with GPS arrows
author: PikaMug
depend: [GPS, Quests]
soft-depend: [Citizens]