name:  GPS-Quests
main: me.pikamug.gpsquests.GPSQuests
version: 1.7
api-version: 1.13
description: Navigate Quests objectives with GPS arrows
author: PikaMug
website: https://github.com/PikaMug/GPS-Quests
depend: [GPS, Quests]
soft-depend: [Citizens]